clarified README, download helper script from github, fixed logging

diff --git a/make-debian-mpd-chroot b/make-debian-mpd-chroot
--- a/make-debian-mpd-chroot
+++ b/make-debian-mpd-chroot
@@ -34,21 +34,25 @@
 
 LANG=C
 
-appname="mpdbuilder"
-#debchroot_mirror="http://ftp.nl.debian.org/debian"
-debchroot_mirror="http://localnet:9999/debian"
+appname="build-latest-mpd-for-debian"
+debchroot_mirror="http://ftp.nl.debian.org/debian"
+#debchroot_mirror="http://localnet:9999/debian"
 debchroot_version="jessie"
 debchroot_arch="amd64"
 debchroot_variant="buildd"
 debchroot_additional_packages="devscripts,coreutils,dpkg-dev,apt-utils,openssh-client,libwww-perl"
-chrootscript_name=build-latest-debian-mpd-package
-chrootscript_path=/usr/local/bin
+helper_script_name=build-latest-debian-mpd-package
+helper_script_downloadpath=/tmp
+helper_script_downloadtarget=${helper_script_downloadpath}/${helper_script_name}
+helper_script_path=/usr/local/bin
 tempchroot_template="${appname}.${debchroot_version}.${debchroot_arch}.XXXX"
+url="https://raw.githubusercontent.com/ronalde/${appname}/master/${helper_script_name}"
 
 scriptname="$(basename ${0})"
 
 function create_chroot {
     ## download and install a virgin debian chroot
+    
     printf "**  performing debootstrap in \`%s' ... " "${debchroot_targetdir}" 2>&1 | tee -a ${logfile}
     res="$(debootstrap \
 	--arch=${debchroot_arch} \
@@ -63,28 +67,45 @@ function create_chroot {
     else
 	printf "done.\n"   2>&1 | tee -a ${logfile}
     fi
+}
+
+function download_helper_script {
+    ## get the latest version of the helper script
+    
+    wget -q "${url}" -O "${helper_script_downloadtarget}" || curl -s -k -o "${helper_script_downloadtarget}" "${url}"
 
 }
 
+function install_helper_script {
+    ## install the helper script inside the chroot, add it to profile
+    ## and set autologon
 
-function install_chrootscript {
-    printf "**  installing the mpd builder script \`%s' inside the chroot ... " "${chrootscript_name}"  2>&1 | tee -a ${logfile}
-    res=$(install --mode=0555 "${chrootscript_name}" "${debchroot_targetdir}${chrootscript_path}")
-    if [[ $? -ne 0 ]]; then
-	printf "ERROR:\n%s\n" "${res}"  2>&1 | tee -a ${logfile}
+    printf "downloading helper script from repository ..."  2>&1 | tee -a ${logfile}
+    res=$(download_helper_script 2>&1 | tee -a ${logfile})
+    if [[ $? -ne 0]]; then
+	printf "\nerror: could not download the the helper script from \n%s\n" "${url}"
 	exit 1
-    else
+    else  
+	printf "done.\n"  2>&1 | tee -a ${logfile}
+	printf "**  installing the mpd builder script \`%s' inside the chroot ... " "${helper_script_name}"  2>&1 | tee -a ${logfile}
+	
+	res=$(install --mode=0555 "${helper_script_downloadtarget}" "${debchroot_targetdir}${helper_script_path}")
+	if [[ $? -ne 0 ]]; then
+	    printf "ERROR:\n%s\n" "${res}"  2>&1 | tee -a ${logfile}
+	    exit 1
+	else
+	    printf "done.\n"  2>&1 | tee -a ${logfile}
+	fi
+	dotprofile="${debchroot_targetdir}/root/.profile"
+	printf "**  insert the script in to \`%s' ... " "${dotprofile}" 2>&1 | tee -a ${logfile}
+	echo "${helper_script_path}/${helper_script_name}" > ${dotprofile}
+	printf "done.\n"  2>&1 | tee -a ${logfile}
+	
+	printf "**  setting autologin for root inside chroot ... " 2>&1 | tee -a ${logfile}
+	console_getty=${debchroot_targetdir}/lib/systemd/system/console-getty.service
+	sed -i 's#^ExecStart.*#ExecStart=-/sbin/agetty --autologin root --noclear --keep-baud console 115200,38400,9600 $TERM#' "${console_getty}"
 	printf "done.\n"  2>&1 | tee -a ${logfile}
     fi
-    dotprofile="${debchroot_targetdir}/root/.profile"
-    printf "**  insert the script in to \`%s' ... " "${dotprofile}" 2>&1 | tee -a ${logfile}
-    echo "${chrootscript_path}/${chrootscript_name}" > ${dotprofile}
-    printf "done.\n"  2>&1 | tee -a ${logfile}
-
-    printf "**  setting autologin for root inside chroot ... " 2>&1 | tee -a ${logfile}
-    console_getty=${debchroot_targetdir}/lib/systemd/system/console-getty.service
-    sed -i 's#^ExecStart.*#ExecStart=-/sbin/agetty --autologin root --noclear --keep-baud console 115200,38400,9600 $TERM#' "${console_getty}"
-    printf "done.\n"  2>&1 | tee -a ${logfile}
     
 }
 
@@ -129,7 +150,7 @@ if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
 	    printf "warning: specified debchroot_targetdir \`%s' does not exist.\n" "${debchroot_targetdir}"
 	else
 	    printf "using exisiting debchroot_targetdir \`%s'\n" "${debchroot_targetdir}"
-	    install_chrootscript
+	    install_helper_script
 	fi
     fi
 else
@@ -146,7 +167,7 @@ else
     else
 	printf "**  debchroot_targetdir is \`%s'.\n" "${debchroot_targetdir}"  2>&1 | tee -a ${logfile}
 	create_chroot && \
-	    install_chrootscript && \
+	    install_helper_script && \
 	    spawn_chroot
     fi
 fi
